### ISSUE TITLE
Perform refactoring from initial MVP Flask Example to Django

### ISSUE THREAD

**Issue by michaelwknott** [michaelwknott/reading-streak-tracker#2]
Since we decided that Django is our framework of choice, the first step (after setting up the code quality tooling) in my view should be to convert the existing Flask-based prototype to an equivalent Django-based prototype.

I am happy to tackle this today, if you are fine with that. 
If you agree, just put me as the Assignee for this one and change the state to "Todo" and I will get to it.

One relevant thing to discuss is our Django project layout, as there are a few possibilities. But we can do that in the discussion of the PR/code feedback as well.

My inclination would be to:
- place templates and static files at the PROJECT level, rather than the APP level
- keep the default sqlite db for local development to begin with and use Postgres only in "production"
- use Whitenoise for handling static assets
- start out with a single "home" app initially that is exposed directly under the root namespace (so still with own urls.py and inclusion of those in`aapo/urls.py`, but keeping them at the root url for now) -> we can split it out later and re-arrange as needed
- I have the practice (which I've never seen in the wild, but I've grown to like a lot) to name the "core" folder i.e. the one that contains the project-wide settings and URL configuration `aapo` (aapo since the double `aa` ensures that it will always show up at the very top of the directory structure, always same name so I have consistency across my personal projects and the full project-name is reflected in the name of the git-repo/local project folder already anyway, and `aapo` because that to me is a convenient mnemonic as it is short for `aapojah` which means "foundation or base" in Finnish which I find a perfect match for the function of that directory. -> would you be open to embrace that? Otherwise I'm happy to adjust

More on aapo/Aapohja (thanks GPT 🙏):
"Aapohja" is a Finnish term that roughly translates to "base" or "foundation" in English. The word is a compound of "aa-" which can signify a base or beginning, and "pohja," which means "bottom" or "foundation."

Let's discuss the rest in the actual code comments then. At this early stage it's still very easy to mold things around as needed.

**Comment by michaelwknott** [comment]
@arnoan More than happy with your recommendations. I really like the `aapo` name for the "core" folder and how this will ensure it stays at the top of the of the directory hierachy.

**Comment by arnoan** [comment]
@michaelwknott 
FYI: I'm working on this now. Will have a (draft) PR ready in 1-2 hours. 

My aim is to have something rudimentary but usable up and running by tomorrow as that's when our reading journey officially commences 🎂 Would be nice to have something ready from the get-go, even if basic. We can then still add all the niceties in the days and weeks to come. Feeling excited 🔥

**Comment by arnoan** [comment]
Small update: My time estimate was off by quite a bit. 
That said, I made quite good progress and will post my current state for this as a PR soon

**Comment by arnoan** [comment]
@michaelwknott 
Update: I have the initial "migration" from the Flask sample to Django up and running now. 
See the latest commits in [the associated PR](https://github.com/michaelwknott/reading-streak-tracker/pull/5) for details. 

Now, for a usable initial MVP, primarily two things remain:
- [x] Combining the calendar & active_coding day logic that currently resides fully isolated in its own app, back with our UserModel
- [ ] Getting a simple initial deploy for this up an running (e.g. on Render.com), so the Fluent Python Reading Journey adventurers can actually access it and make use of it 😉 

I am planning to take these on today – and think they can be subsumed under the "perform initial refactoring" issue still. 
Would you like to hop on a quick 5-10mins call sometime today and discuss the current state?
